# 특이점(outlier)
forbes = read.table("forbes.txt",header=T)
forbes$Lpress = 100*log10(forbes$press)
head(forbes)
plot(forbes$temp, forbes$Lpress, pch = 19)
identify(forbes$temp, forbes$Lpress)
forbes.lm = lm(Lpress~temp, data=forbes)
summary(forbes.lm)
anova(forbes.lm)
forbes.res = ls.diag(forbes.lm)
names(forbes.res)
resid.result=cbind(forbes.res$std.res, forbes.res$stud.res, forbes.res$hat)
colnames(resid.result) = c("standardized resid", "studentized resid", "Hat")
resid.result=round(resid.result, 3)
print(resid.result)
2*17*(1-pt(12.374, 14)) # p값이 매우 작으므로 특이값으로 판단
qt(0.01/(2*17),14) # 유의수준 0.01에서 기각치 계산
rstudent(forbes.lm) # 스튜던트화 잔차 
library(car)
outlierTest(forbes.lm)

# 영향력 있는 관측값(influential observation)
prater = read.table("prater.txt", header=T)
head(prater,2)
prater.lm = lm(Y~X1+X2+X3+X4, data=prater)
summary(prater.lm)
start.lm = lm(Y~1, data=prater)
full.lm = lm(Y~X1+X2+X3+X4, data=prater)
step(start.lm, scope=list(upper=full.lm), data=prater, direction="both")

soil = read.table("soil.txt", header=T)
head(soil,3)
soil.lm = lm(SL~SG+LOBS+PGC, data=soil)
summary(soil.lm)
anova(soil.lm)
plot(soil.lm$fitted, soil.lm$resid, pch=19)
identify(soil.lm$fitted, soil.lm$resid)
soil.diag = ls.diag(soil.lm)
names(soil.diag)
diag.st=cbind(soil.diag$hat, soil.diag$std.res, soil.diag$stud.res, soil.diag$cooks)
colnames(diag.st) = c("Hii","ri","ti","Di")
round(diag.st,3)
Di = cooks.distance(soil.lm)
round(Di,3)
outlierTest(soil.lm)

# Problem2
health = read.csv("p162.csv", header=T)
head(health,3)
health.lm = lm(Y~X1+X2+X3+X4, data=health)
summary(health.lm)
start.lm = lm(Y~1, data=health)
full.lm = lm(Y~X1+X2+X3+X4, data=health)
step(start.lm, scope=list(upper=full.lm), data=health, direction="both")
health.lm = lm(Y~X1+X3+X4, data=health) # 최종 회귀분석식
plot(health.lm$fitted, health.lm$resid, pch=19)
summary(health.lm)
anova(health.lm)
names(health.lm)
health.ls = ls.diag(health.lm)
health.st = cbind(health.lm$fitted, health.ls$stud.res)
colnames(health.st) = c("fitted", "stud.res")
health.st = as.data.frame(health.st)
plot(health.st$fitted, health.st$stud.res, pch=19)
outlierTest(health.lm)
identify(health.st$fitted, health.st$stud.res)
rstudent(health.lm)
2*30*(1-pt(1.86243, 25))
